### ISSUE TITLE
Enhance kustomization readiness checks

### ISSUE THREAD

**Issue by mxmxchere** [SovereignCloudStack/moin-cluster-config#6]
Kustomizations get into the ready state too fast, therefore dependsOn does not work as nicely as it is supposed to do. It is possible to let flux wait for more finegrained conditions using
`ks.spec.wait`

**Comment by chess-knight** [comment]
Additionally, [.spec.healthChecks](https://fluxcd.io/flux/components/kustomize/kustomizations/#health-checks) can be used. You can check the [k8s-harbor](https://github.com/SovereignCloudStack/k8s-harbor/blob/main/envs/public/public.yaml) repo for example.
